env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier # this should be last
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/prefer-default-export: 0
